# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-22 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiku',
            name='rightanswer',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='tiku',
            name='pic',
            field=models.ImageField(blank=True, upload_to='imgfiles'),
        ),
    ]
