# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0002_auto_20180422_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiku',
            name='pic',
        ),
    ]
